server: 
  port: 8110

info:
  name: AdminService

spring:
  application:
    name: AdminService
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

logging:
  path: logfile
