server: 
  port: 8110

info:
  name: AdminService

spring:
  boot:
    admin:
      url: http://localhost:8110
  application:
    name: AdminService
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

logging:
  path: logfile
