server:
  port: 8000

spring:
  application:
    name: APIGateWay

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: API Gateway

logging:
  path: logfile
