server:
  port: 8200

spring:
  application:
    name: ContentsService
  output:
    ansi:
      enabled: ALWAYS
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: ContentsService

logging:
  path: logfile
