server:
  port: 8200

spring:
  boot:
    admin:
      url: http://localhost:8110
  application:
    name: ContentsService
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: ContentsService

logging:
  path: logfile
