server: 
  port: 8100

info:
  name: ServiceDiscovery

spring:
  application:
    name: ServiceDiscovery

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
      
logging:
  path: logfile
