server: 
  port: 8100

info:
  name: ServiceDiscovery

spring:
  boot:
    admin:
      context-path: /bootadmin
      url: http://localhost:8100
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    healthcheck:
      enabled: false
      
