server:
  port: 9999
  contextPath: /uaa

spring:
  application:
    name: AuthService
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: Authorization and Resource Service

logging:
  path: logfile

security:
  basic:
    enabled: true
  oauth2:
    client:
      clientId: proto
      clientSecret: protoSecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: proto
  user:
    password: userSecret

