server:
  port: 8200

spring:
  boot:
    admin:
      url: http://localhost:8100

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: ProtoMicroService

